// Automatically generated by makemoduledefs.py.

extern const struct _mp_obj_module_t mp_module_array;
#undef MODULE_DEF_ARRAY
#define MODULE_DEF_ARRAY { MP_ROM_QSTR(MP_QSTR_array), MP_ROM_PTR(&mp_module_array) },

extern const struct _mp_obj_module_t mp_module_collections;
#undef MODULE_DEF_COLLECTIONS
#define MODULE_DEF_COLLECTIONS { MP_ROM_QSTR(MP_QSTR_collections), MP_ROM_PTR(&mp_module_collections) },

extern const struct _mp_obj_module_t mp_module_errno;
#undef MODULE_DEF_ERRNO
#define MODULE_DEF_ERRNO { MP_ROM_QSTR(MP_QSTR_errno), MP_ROM_PTR(&mp_module_errno) },

extern const struct _mp_obj_module_t mp_module_io;
#undef MODULE_DEF_IO
#define MODULE_DEF_IO { MP_ROM_QSTR(MP_QSTR_io), MP_ROM_PTR(&mp_module_io) },

extern const struct _mp_obj_module_t mp_module_machine;
#undef MODULE_DEF_MACHINE
#define MODULE_DEF_MACHINE { MP_ROM_QSTR(MP_QSTR_machine), MP_ROM_PTR(&mp_module_machine) },

extern const struct _mp_obj_module_t mp_module_os;
#undef MODULE_DEF_OS
#define MODULE_DEF_OS { MP_ROM_QSTR(MP_QSTR_os), MP_ROM_PTR(&mp_module_os) },

extern const struct _mp_obj_module_t mp_module_platform;
#undef MODULE_DEF_PLATFORM
#define MODULE_DEF_PLATFORM { MP_ROM_QSTR(MP_QSTR_platform), MP_ROM_PTR(&mp_module_platform) },

extern const struct _mp_obj_module_t mp_module_struct;
#undef MODULE_DEF_STRUCT
#define MODULE_DEF_STRUCT { MP_ROM_QSTR(MP_QSTR_struct), MP_ROM_PTR(&mp_module_struct) },

extern const struct _mp_obj_module_t mp_module_time;
#undef MODULE_DEF_TIME
#define MODULE_DEF_TIME { MP_ROM_QSTR(MP_QSTR_time), MP_ROM_PTR(&mp_module_time) },

extern const struct _mp_obj_module_t mp_module___main__;
#undef MODULE_DEF___MAIN__
#define MODULE_DEF___MAIN__ { MP_ROM_QSTR(MP_QSTR___main__), MP_ROM_PTR(&mp_module___main__) },

extern const struct _mp_obj_module_t mp_module_builtins;
#undef MODULE_DEF_BUILTINS
#define MODULE_DEF_BUILTINS { MP_ROM_QSTR(MP_QSTR_builtins), MP_ROM_PTR(&mp_module_builtins) },

extern const struct _mp_obj_module_t mp_module_cmath;
#undef MODULE_DEF_CMATH
#define MODULE_DEF_CMATH { MP_ROM_QSTR(MP_QSTR_cmath), MP_ROM_PTR(&mp_module_cmath) },

extern const struct _mp_obj_module_t mp_module_gc;
#undef MODULE_DEF_GC
#define MODULE_DEF_GC { MP_ROM_QSTR(MP_QSTR_gc), MP_ROM_PTR(&mp_module_gc) },

extern const struct _mp_obj_module_t gif_module;
#undef MODULE_DEF_GIF
#define MODULE_DEF_GIF { MP_ROM_QSTR(MP_QSTR_gif), MP_ROM_PTR(&gif_module) },

extern const struct _mp_obj_module_t image_module;
#undef MODULE_DEF_IMAGE
#define MODULE_DEF_IMAGE { MP_ROM_QSTR(MP_QSTR_image), MP_ROM_PTR(&image_module) },

extern const struct _mp_obj_module_t mp_module_math;
#undef MODULE_DEF_MATH
#define MODULE_DEF_MATH { MP_ROM_QSTR(MP_QSTR_math), MP_ROM_PTR(&mp_module_math) },

extern const struct _mp_obj_module_t mp_module_micropython;
#undef MODULE_DEF_MICROPYTHON
#define MODULE_DEF_MICROPYTHON { MP_ROM_QSTR(MP_QSTR_micropython), MP_ROM_PTR(&mp_module_micropython) },

extern const struct _mp_obj_module_t mjpeg_module;
#undef MODULE_DEF_MJPEG
#define MODULE_DEF_MJPEG { MP_ROM_QSTR(MP_QSTR_mjpeg), MP_ROM_PTR(&mjpeg_module) },

extern const struct _mp_obj_module_t omv_module;
#undef MODULE_DEF_OMV
#define MODULE_DEF_OMV { MP_ROM_QSTR(MP_QSTR_omv), MP_ROM_PTR(&omv_module) },

extern const struct _mp_obj_module_t omv_csi_module;
#undef MODULE_DEF_SENSOR
#define MODULE_DEF_SENSOR { MP_ROM_QSTR(MP_QSTR_sensor), MP_ROM_PTR(&omv_csi_module) },

extern const struct _mp_obj_module_t mp_module_sys;
#undef MODULE_DEF_SYS
#define MODULE_DEF_SYS { MP_ROM_QSTR(MP_QSTR_sys), MP_ROM_PTR(&mp_module_sys) },

extern const struct _mp_obj_module_t mp_module_uctypes;
#undef MODULE_DEF_UCTYPES
#define MODULE_DEF_UCTYPES { MP_ROM_QSTR(MP_QSTR_uctypes), MP_ROM_PTR(&mp_module_uctypes) },

extern const struct _mp_obj_module_t ulab_user_cmodule;
#undef MODULE_DEF_ULAB
#define MODULE_DEF_ULAB { MP_ROM_QSTR(MP_QSTR_ulab), MP_ROM_PTR(&ulab_user_cmodule) },


#define MICROPY_REGISTERED_MODULES \
    MODULE_DEF_BUILTINS \
    MODULE_DEF_CMATH \
    MODULE_DEF_GC \
    MODULE_DEF_GIF \
    MODULE_DEF_IMAGE \
    MODULE_DEF_MATH \
    MODULE_DEF_MICROPYTHON \
    MODULE_DEF_MJPEG \
    MODULE_DEF_OMV \
    MODULE_DEF_SENSOR \
    MODULE_DEF_SYS \
    MODULE_DEF_UCTYPES \
    MODULE_DEF_ULAB \
    MODULE_DEF___MAIN__ \
// MICROPY_REGISTERED_MODULES

#define MICROPY_HAVE_REGISTERED_EXTENSIBLE_MODULES  9

#define MICROPY_REGISTERED_EXTENSIBLE_MODULES \
    MODULE_DEF_ARRAY \
    MODULE_DEF_COLLECTIONS \
    MODULE_DEF_ERRNO \
    MODULE_DEF_IO \
    MODULE_DEF_MACHINE \
    MODULE_DEF_OS \
    MODULE_DEF_PLATFORM \
    MODULE_DEF_STRUCT \
    MODULE_DEF_TIME \
// MICROPY_REGISTERED_EXTENSIBLE_MODULES

extern void mp_module_sys_attr(mp_obj_t self_in, qstr attr, mp_obj_t *dest);
#define MICROPY_MODULE_DELEGATIONS \
    { MP_ROM_PTR(&mp_module_sys), mp_module_sys_attr }, \
// MICROPY_MODULE_DELEGATIONS
