################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
ra/arm/CMSIS-DSP/Source/BasicMathFunctions \
ra/arm/CMSIS-DSP/Source/BayesFunctions \
ra/arm/CMSIS-DSP/Source/CommonTables \
ra/arm/CMSIS-DSP/Source/ComplexMathFunctions \
ra/arm/CMSIS-DSP/Source/ControllerFunctions \
ra/arm/CMSIS-DSP/Source/DistanceFunctions \
ra/arm/CMSIS-DSP/Source/FastMathFunctions \
ra/arm/CMSIS-DSP/Source/FilteringFunctions \
ra/arm/CMSIS-DSP/Source/InterpolationFunctions \
ra/arm/CMSIS-DSP/Source/MatrixFunctions \
ra/arm/CMSIS-DSP/Source/QuaternionMathFunctions \
ra/arm/CMSIS-DSP/Source/SVMFunctions \
ra/arm/CMSIS-DSP/Source/StatisticsFunctions \
ra/arm/CMSIS-DSP/Source/SupportFunctions \
ra/arm/CMSIS-DSP/Source/TransformFunctions \
ra/arm/CMSIS-DSP/Source/WindowFunctions \
ra/aws/FreeRTOS/FreeRTOS/Source \
ra/aws/FreeRTOS/FreeRTOS/Source/portable/MemMang \
ra/fsp/src/bsp/cmsis/Device/RENESAS/Source \
ra/fsp/src/bsp/mcu/all \
ra/fsp/src/bsp/mcu/ra8p1 \
ra/fsp/src/r_dmac \
ra/fsp/src/r_gpt \
ra/fsp/src/r_iic_b_master \
ra/fsp/src/r_iic_master \
ra/fsp/src/r_ioport \
ra/fsp/src/r_mipi_csi \
ra/fsp/src/r_mipi_phy \
ra/fsp/src/r_mram \
ra/fsp/src/r_ospi_b \
ra/fsp/src/r_rtc \
ra/fsp/src/r_sci_b_uart \
ra/fsp/src/r_spi_b \
ra/fsp/src/r_usb_pcdc/src \
ra/fsp/src/r_vin \
ra/fsp/src/rm_freertos_port \
ra_gen \
src/MicroPython/drivers/bus \
src/MicroPython/drivers/memory \
src/MicroPython/extmod \
src/MicroPython/lib/oofatfs \
src/MicroPython/lib/tinyusb/hw/bsp \
src/MicroPython/lib/tinyusb/src/class/cdc \
src/MicroPython/lib/tinyusb/src/class/dfu \
src/MicroPython/lib/tinyusb/src/class/hid \
src/MicroPython/lib/tinyusb/src/class/midi \
src/MicroPython/lib/tinyusb/src/class/msc \
src/MicroPython/lib/tinyusb/src/class/usbtmc \
src/MicroPython/lib/tinyusb/src/class/vendor \
src/MicroPython/lib/tinyusb/src/common \
src/MicroPython/lib/tinyusb/src/device \
src/MicroPython/lib/tinyusb/src/portable/renesas/rusb2 \
src/MicroPython/lib/tinyusb/src \
src/MicroPython/ports/renesas-ra/drivers \
src/MicroPython/ports/renesas-ra \
src/MicroPython/py \
src/MicroPython/shared/libc \
src/MicroPython/shared/readline \
src/MicroPython/shared/runtime \
src/MicroPython/shared/timeutils \
src/MicroPython/shared/tinyusb \
src/OpenMV/common \
src/OpenMV/drivers/sensors \
src/OpenMV/lib/imlib \
src/OpenMV/lib/openpdm \
src/OpenMV/modules \
src/OpenMV/modules/ulab/code \
src/OpenMV/modules/ulab/code/numpy \
src/OpenMV/modules/ulab/code/numpy/carray \
src/OpenMV/modules/ulab/code/numpy/fft \
src/OpenMV/modules/ulab/code/numpy/io \
src/OpenMV/modules/ulab/code/numpy/linalg \
src/OpenMV/modules/ulab/code/numpy/ndarray \
src/OpenMV/modules/ulab/code/numpy/random \
src/OpenMV/modules/ulab/code/scipy/integrate \
src/OpenMV/modules/ulab/code/scipy/linalg \
src/OpenMV/modules/ulab/code/scipy/optimize \
src/OpenMV/modules/ulab/code/scipy \
src/OpenMV/modules/ulab/code/scipy/signal \
src/OpenMV/modules/ulab/code/scipy/special \
src/OpenMV/modules/ulab/code/user \
src/OpenMV/modules/ulab/code/utils \
src/OpenMV/modules/unittests \
src/OpenMV/ports/ra8 \
src/OpenMV/protocol \
src \

